import type { CSSProperties } from "react";

export const s = {
  wrap: { padding: "24px 28px 44px" } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 14, marginBottom: 8 } satisfies CSSProperties,
  title: { fontSize: 18, fontWeight: 700, letterSpacing: "-0.01em" } satisfies CSSProperties,
  enabledBadge: {
    fontSize: 12,
    fontWeight: 600,
    padding: "3px 8px",
    borderRadius: 5,
    background: "var(--accent-bg)",
    color: "var(--accent)",
  } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 200,
    marginLeft: "auto",
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)", marginBottom: 16 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: (linked: boolean, dragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: dragging ? "var(--bg-hover)" : linked ? "var(--bg-elevated)" : "var(--bg-surface)",
    opacity: dragging ? 0.85 : 1,
    boxShadow: dragging ? "var(--shadow-modal)" : "none",
  }),
  handle: {
    color: "var(--text-muted)",
    cursor: "grab",
    display: "inline-flex",
    padding: 2,
  } satisfies CSSProperties,
  name: {
    flex: 1,
    fontSize: 13.5,
    fontFamily: "var(--font-mono, ui-monospace, SFMono-Regular, monospace)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  typeBadge: (color: string): CSSProperties => ({
    fontSize: 11,
    fontWeight: 600,
    color,
    background: color + "1f",
    padding: "2px 8px",
    borderRadius: 4,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  }),
  empty: {
    padding: "32px 20px",
    textAlign: "center" as const,
    fontSize: 13,
    color: "var(--text-muted)",
    border: "1px dashed var(--border)",
    borderRadius: 8,
  } satisfies CSSProperties,
} as const;
