import type { CSSProperties } from "react";

/** Co-located styles for FindingsCell (per design's screen_dashboard.jsx). */
export const s = {
  cell: {
    position: "relative" as const,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    width: "fit-content",
    cursor: "help",
  } satisfies CSSProperties,
  empty: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  pill: (color: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    fontSize: 11.5,
    fontWeight: 600,
    color,
    borderBottom: "1px dotted " + color,
    paddingBottom: 1,
  }),
  tooltip: {
    position: "fixed" as const,
    zIndex: 9999,
    width: 360,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 10,
    boxShadow: "var(--shadow-modal)",
    padding: 12,
    cursor: "default",
    textAlign: "left" as const,
    pointerEvents: "none" as const,
  } satisfies CSSProperties,
  tooltipHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase" as const,
    marginBottom: 9,
  } satisfies CSSProperties,
  tooltipList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 9,
    maxHeight: 300,
    overflow: "auto",
  } satisfies CSSProperties,
  tooltipItem: (last: boolean): CSSProperties => ({
    paddingBottom: last ? 0 : 9,
    borderBottom: last ? "none" : "1px solid var(--border)",
  }),
  tooltipTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    flexWrap: "wrap" as const,
  } satisfies CSSProperties,
  tooltipTitle: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  tooltipMetaRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    margin: "5px 0 0",
  } satisfies CSSProperties,
  tooltipFileLink: {
    fontSize: 11,
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  tooltipConfidence: {
    fontSize: 11,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  tooltipRationale: {
    fontSize: 11.5,
    color: "var(--text-secondary)",
    lineHeight: 1.45,
    marginTop: 5,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
    overflow: "hidden",
  } satisfies CSSProperties,
} as const;
