import type { CSSProperties } from "react";

export const s = {
  pane: { padding: "20px 28px 44px" } satisfies CSSProperties,
  bodyHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "8px 12px",
    fontSize: 12,
    color: "var(--text-muted)",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderBottom: "none",
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
    fontFamily: "var(--font-mono)",
  } satisfies CSSProperties,
  bodyFilename: { flex: 1 } satisfies CSSProperties,
  bodyUnsaved: {
    fontSize: 11,
    color: "var(--sev-warning, #f59e0b)",
    background: "rgba(245, 158, 11, 0.12)",
    border: "1px solid rgba(245, 158, 11, 0.35)",
    padding: "1px 8px",
    borderRadius: 4,
  } satisfies CSSProperties,
  editorRow: {
    display: "flex",
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    lineHeight: 1.55,
    border: "1px solid var(--border-strong)",
    borderTop: "none",
    borderBottomLeftRadius: 7,
    borderBottomRightRadius: 7,
    background: "var(--bg-elevated)",
    overflow: "hidden",
  } satisfies CSSProperties,
  gutter: {
    padding: "10px 8px 10px 12px",
    color: "var(--text-muted)",
    textAlign: "right" as const,
    userSelect: "none" as const,
    whiteSpace: "pre" as const,
    borderRight: "1px solid var(--border)",
    minWidth: 36,
    fontSize: 12,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  editorTextarea: {
    flex: 1,
    padding: "10px 12px",
    background: "transparent",
    color: "var(--text-primary)",
    border: "none",
    outline: "none",
    resize: "vertical" as const,
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    lineHeight: 1.55,
  } satisfies CSSProperties,
  saveHint: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginRight: "auto",
  } satisfies CSSProperties,
  sectionTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-secondary)",
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    marginBottom: 12,
  } satisfies CSSProperties,
  bodyTabs: { display: "flex", gap: 6, marginBottom: 8 } satisfies CSSProperties,
  bodyTab: (active: boolean): CSSProperties => ({
    padding: "5px 12px",
    fontSize: 12.5,
    fontWeight: 600,
    background: "none",
    border: "none",
    borderBottom: `2px solid ${active ? "var(--accent)" : "transparent"}`,
    color: active ? "var(--text-primary)" : "var(--text-muted)",
    cursor: "pointer",
  }),
  preview: {
    minHeight: 260,
    padding: 16,
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  tokenCounter: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 24,
    padding: "16px 0",
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  versionRow: (current: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    padding: "14px 16px",
    border: `1px solid ${current ? "var(--accent)" : "var(--border)"}`,
    borderRadius: 8,
    background: current ? "var(--accent-bg)" : "var(--bg-surface)",
    marginBottom: 10,
  }),
  versionNumber: {
    fontSize: 13,
    fontWeight: 700,
    fontFamily: "var(--font-mono)",
    color: "var(--accent)",
    minWidth: 36,
  } satisfies CSSProperties,
  versionMeta: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  versionTopRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
    flexWrap: "wrap" as const,
  } satisfies CSSProperties,
  versionDate: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  currentBadge: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--accent)",
    background: "var(--accent-bg)",
    border: "1px solid var(--accent)",
    padding: "1px 8px",
    borderRadius: 4,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
  } satisfies CSSProperties,
  diffStats: {
    fontSize: 12,
    fontFamily: "var(--font-mono)",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  diffPlus: { color: "var(--sev-ok, #10b981)" } satisfies CSSProperties,
  diffMinus: { color: "var(--sev-critical, #ef4444)" } satisfies CSSProperties,
  versionActions: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  versionBody: {
    fontSize: 12.5,
    fontFamily: "var(--font-mono)",
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap" as const,
    maxHeight: 240,
    overflow: "auto",
    padding: 10,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 6,
  } satisfies CSSProperties,
  diffBlock: {
    fontSize: 12.5,
    fontFamily: "var(--font-mono)",
    lineHeight: 1.55,
    maxHeight: 320,
    overflow: "auto",
    padding: 0,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 6,
  } satisfies CSSProperties,
  diffLine: (kind: "eq" | "add" | "del"): CSSProperties => ({
    display: "flex",
    padding: "1px 10px",
    background:
      kind === "add"
        ? "rgba(16, 185, 129, 0.08)"
        : kind === "del"
          ? "rgba(239, 68, 68, 0.08)"
          : "transparent",
    color:
      kind === "add"
        ? "var(--sev-ok, #10b981)"
        : kind === "del"
          ? "var(--sev-critical, #ef4444)"
          : "var(--text-secondary)",
  }),
  diffPrefix: { width: 14, flexShrink: 0, userSelect: "none" as const } satisfies CSSProperties,
  diffText: { whiteSpace: "pre-wrap" as const, flex: 1 } satisfies CSSProperties,
  viewToggle: { display: "flex", gap: 4 } satisfies CSSProperties,
  viewToggleBtn: (active: boolean): CSSProperties => ({
    padding: "3px 9px",
    fontSize: 11.5,
    fontWeight: 600,
    background: active ? "var(--bg-elevated)" : "transparent",
    border: `1px solid ${active ? "var(--border-strong)" : "var(--border)"}`,
    borderRadius: 5,
    color: active ? "var(--text-primary)" : "var(--text-muted)",
    cursor: "pointer",
  }),
  statGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 14,
  } satisfies CSSProperties,
  statCard: {
    padding: 18,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  statLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-muted)",
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    marginBottom: 8,
  } satisfies CSSProperties,
  statValue: {
    fontSize: 28,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
} as const;
