import type { CSSProperties } from "react";

export const s = {
  pane: { padding: "20px 28px 44px" } satisfies CSSProperties,
  bodyHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "8px 12px",
    fontSize: 12,
    color: "var(--text-muted)",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderBottom: "none",
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
    fontFamily: "var(--font-mono)",
  } satisfies CSSProperties,
  bodyFilename: { flex: 1 } satisfies CSSProperties,
  bodyUnsaved: {
    fontSize: 11,
    color: "var(--sev-warning, #f59e0b)",
    background: "rgba(245, 158, 11, 0.12)",
    border: "1px solid rgba(245, 158, 11, 0.35)",
    padding: "1px 8px",
    borderRadius: 4,
  } satisfies CSSProperties,
  editorRow: {
    display: "flex",
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    lineHeight: 1.55,
    border: "1px solid var(--border-strong)",
    borderTop: "none",
    borderBottomLeftRadius: 7,
    borderBottomRightRadius: 7,
    background: "var(--bg-elevated)",
    overflow: "hidden",
  } satisfies CSSProperties,
  gutter: {
    padding: "10px 8px 10px 12px",
    color: "var(--text-muted)",
    textAlign: "right" as const,
    userSelect: "none" as const,
    whiteSpace: "pre" as const,
    borderRight: "1px solid var(--border)",
    minWidth: 36,
    fontSize: 12,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  editorTextarea: {
    flex: 1,
    padding: "10px 12px",
    background: "transparent",
    color: "var(--text-primary)",
    border: "none",
    outline: "none",
    resize: "vertical" as const,
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    lineHeight: 1.55,
  } satisfies CSSProperties,
  saveHint: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginRight: "auto",
  } satisfies CSSProperties,
  sectionTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-secondary)",
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    marginBottom: 12,
  } satisfies CSSProperties,
  bodyTabs: { display: "flex", gap: 6, marginBottom: 8 } satisfies CSSProperties,
  bodyTab: (active: boolean): CSSProperties => ({
    padding: "5px 12px",
    fontSize: 12.5,
    fontWeight: 600,
    background: "none",
    border: "none",
    borderBottom: `2px solid ${active ? "var(--accent)" : "transparent"}`,
    color: active ? "var(--text-primary)" : "var(--text-muted)",
    cursor: "pointer",
  }),
  preview: {
    minHeight: 260,
    padding: 16,
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  tokenCounter: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 24,
    padding: "16px 0",
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  versionRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    padding: "14px 16px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    marginBottom: 10,
  } satisfies CSSProperties,
  versionNumber: {
    fontSize: 13,
    fontWeight: 700,
    fontFamily: "var(--font-mono)",
    color: "var(--accent)",
    minWidth: 36,
  } satisfies CSSProperties,
  versionMeta: { flex: 1 } satisfies CSSProperties,
  versionDate: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  versionBody: {
    fontSize: 12.5,
    fontFamily: "var(--font-mono)",
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap" as const,
    maxHeight: 200,
    overflow: "auto",
    padding: 10,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 6,
  } satisfies CSSProperties,
  statGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 14,
  } satisfies CSSProperties,
  statCard: {
    padding: 18,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  statLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-muted)",
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    marginBottom: 8,
  } satisfies CSSProperties,
  statValue: {
    fontSize: 28,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
} as const;
